### PR TITLE
Add styles to ui

### PR DESCRIPTION
**Pull request by bolah2009**
## React Bookstore Project: Milestone 5

- Add more styles to fit the style guide
- Add persistent storage with local storage

### Deploy Preview:

https://deploy-preview-5--bolah-react-bookstore.netlify.com/

### Screenshot

| Large Screen | Small Screen |
| :---: | :---: |
| Book Store |  Book Store |

### CODE REVIEW

**Review by AdnanAfsari — CHANGES_REQUESTED** [review]
**Status: Changes Required**

Hello @bolah2009 ✋ 

Nice work 👏 . Looks good so far but I think UI of the app should look like the provided one from the requirement and you have few more design left to do. All of them should not be functional but the UI should look like the design.

Please make this change and submit for another review.

Happy Coding
Adnan Afsari

**Comment by bolah2009** [comment]
Hi @AdnanAfsari 

>  I think UI of the app should look like the provided one from the requirement and you have few more design left to do.

I am reading this differently? :thinking: 

> Notice there are features that you haven’t implemented yet (e.g. Comments). **Feel free to ignore them.**

I didn't include them as they are not functional.
I think this shouldn't be a required change.

Thanks for the review. :+1:

**Comment by AdnanAfsari** [comment]
Hello @bolah2009 

Screenshot 2019-11-21 at 10 11 40 PM
 I am actually confused about it. they asked to do the design as it is and ignore those features from  making it functional because we have not implemented yet- this how i read it 😄 .

**Comment by bolah2009** [comment]
I understand. I think the requirements may not be clear enough on this.

I really don't want to introduce redundant sections to the project.
But all the components on this project was styled based on the design.
> Implement the styling of the different components based on the design

**Comment by AdnanAfsari** [comment]
Hello @bolah2009 

I understand. as we talked about it on chat, I am giving a 👍 . You are good to go 😄 .

**Pull request merged**
